version: '2'
services:
  codescene-ci-cd:
    build: . 
    ports:
      - "3005:3005"
    environment:
      - CODESCENE_CI_CD_GITHUB_SECRET=${CODESCENE_CI_CD_GITHUB_SECRET}
      - CODESCENE_CI_CD_GITHUB_TOKEN=${CODESCENE_CI_CD_GITHUB_TOKEN}
      - CODESCENE_URL=${CODESCENE_URL}
