version: 2.1

jobs:
  codescene-ci-cd:
    docker:
      - image: empear/codescene-ci-cd
    steps:
      - checkout
      - run: 
          name: CodeScene Delta Analysis
          command:
            if [[ -z $CIRCLE_PULL_REQUEST ]] ; then 
              export PREVIOUS_COMMIT=$(git rev-parse HEAD^);
              codescene-ci-cd.sh
                --codescene-delta-analysis-url CODESCENE_DELTA_ANALYSIS_URL
                --codescene-user $CODESCENE_USER
                --codescene-password $CODESCENE_PASSWORD
                --codescene-repository $CIRCLE_PROJECT_REPONAME
                --pass-on-failed-analysis
                --fail-on-failed-goal
                --fail-on-declining-code-health
                --analyze-individual-commits
                --coupling-threshold-percent $CODESCENE_COUPLING_THRESHOLD_PERCENT
                --risk-threshold $CODESCENE_RISK_THRESHOLD    
                --current-commit $CIRCLE_SHA1
                --previous-commit $PREVIOUS_COMMIT
                --http-timeout $CODESCENE_HTTP_TIMEOUT
                --log-result;
            else
              export PREVIOUS_COMMIT=$(git rev-parse HEAD^);
              export PULL_REQUEST_ID=${CIRCLE_PULL_REQUEST##*/};
              codescene-ci-cd.sh
                --codescene-delta-analysis-url $CODESCENE_DELTA_ANALYSIS_URL
                --codescene-user $CODESCENE_USER
                --codescene-password $CODESCENE_PASSWORD
                --codescene-repository $CIRCLE_PROJECT_REPONAME
                --pass-on-failed-analysis
                --fail-on-failed-goal
                --fail-on-declining-code-health
                --analyze-branch-diff
                --coupling-threshold-percent $CODESCENE_COUPLING_THRESHOLD_PERCENT
                --risk-threshold $CODESCENE_RISK_THRESHOLD
                --current-commit $CIRCLE_SHA1
                --base-revision master
                --create-github-comment
                --github-api-url $CODESCENE_GITHUB_API_URL
                --github-api-token $CODESCENE_GITHUB_API_TOKEN
                --github-owner $CIRCLE_PROJECT_USERNAME
                --github-repo $CIRCLE_PROJECT_REPONAME
                --github-pull-request-id $PULL_REQUEST_ID
                --http-timeout $CODESCENE_HTTP_TIMEOUT
                --log-result;
            fi  

workflows:
  version: 2
  my-workflow:
    jobs:
      - codescene-ci-cd:
          context: codescene-ci-cd
